### PR TITLE
Add sandbox.bio

### PR DESCRIPTION
**Pull request by robertaboukhalil**
Hi there! I maintain https://sandbox.bio and thought it would be a relevant resource to add to your list 🙂 

It features interactive CLI tutorials and there is no repo to link to, so the formatting looks a little different than the other linkouts; let me know if that's ok.

### CODE REVIEW

**Comment by GeertvanGeest** [comment]
Wow, really nice resource and I'd be definitely motivated to spread it! 
However, we aim to have only repositories with open course source files in this list because we want to promote FAIRness. At a later stage we want to transform this into a web app that parses the github api. Is there a public repo with source files for sandbox.bio? And have you already tried to add it to [Awesome-Bioinformatics](https://github.com/danielecook/Awesome-Bioinformatics)?

**Comment by cinnetcrash** [comment]
Can we re-configure sandbox.bio for training packages or workflows especially for LMICs? I love sandbox.bio? I was showing sandbox for people who are not familiar with these terms and I also want to help with language options (Turkish for example), too?

**Comment by GeertvanGeest** [comment]
@cinnetcrash please use https://github.com/sandbox-bio/feedback/discussions for questions related to sandbox.bio. 

> Can we re-configure sandbox.bio for training packages or workflows especially for LMICs? I love sandbox.bio? I was showing sandbox for people who are not familiar with these terms and I also want to help with language options (Turkish for example), too?

**Comment by robertaboukhalil** [comment]
Thanks Geert! I'm planning to have a separate repo with tutorial contents, I'll send another PR once that's ready

**Pull request closed without merging**
